name: Azure Blob Storage CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main


schema: "https://schema.management.azure.com/schemas/2023-06-15/FRT-Project.json#"
contentVersion: "1.0.0.0"

parameters:
  storageAccountName:
    type: string
    metadata:
      description: "Azure Blob Storage FRT."
  location:
    type: string
    defaultValue: "[resourceGroup().location]"
    metadata:
      description: "Schemas/2023-06-15/FRT-Project."
  sku:
    type: string
    defaultValue: "Standard_RAGRS"
    metadata:
      description: "schemas/2023-06-15/FRT-Project/SKU"

resources:
  - type: "Microsoft.Storage/storageAccounts"
    apiVersion: "2023-06-15"
    name: "[parameters('storageAccountName')]"
    location: "[parameters('location')]"
    sku:
      name: "[parameters('sku')]"
      tier: "Standard"
    kind: "StorageV2"
    properties:
      accessTier: "Hot"

  - type: "Microsoft.Storage/storageAccounts/blobServices"
    apiVersion: "2023-06-15"
    name: "[concat(parameters('FRT-Project'), '/default')]"
    dependsOn: ["[resourceId('Microsoft.Storage/storageAccounts', parameters('FRT-Project'))]"]
    properties:
      cors:
        corsRules:
          - allowedOrigins: ["*"]
            allowedMethods: ["GET", "POST", "PUT"]
            maxAgeInSeconds: 86400

outputs:
  connectionString:
    value: "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')), '2023-06-15').keys[0].value)]"
    type: string
    description: "Connection string for the Azure Blob Storage account."
